server:
  port: 8080

spring:
  application:
    name: homework
  profiles:
#    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:homework
    username: root
    password: test1
    initialization-mode: always
    initialize: true
    data: classpath:category.sql, classpath:product.sql
  jooq:
    sql-dialect: h2     
  

  h2:
    console:
      enabled: true
      path: /h2

logging:
    pattern:
        console: "%d %-5level %logger : %msg%n"
    level:
        org.springframework.web: DEBUG
        com: DEBUG
        org.jooq.tools.LoggerListener: DEBUG